# -*- coding: utf-8 -*-
"""Image processing basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rvQkqsTXOMmoOKA6j0x8INmWGAr7PsoR
"""

import numpy as np
import matplotlib.pyplot as plt
import skimage.io as io

demoimg = io.imread('demo.jpg')

io.imshow('demo.jpg')

from copy import deepcopy

red_channel = deepcopy(demoimg)

red_channel[:,:,1] =0
red_channel[:,:,2] =0

io.imshow(red_channel)

import cv2
from google.colab.patches import cv2_imshow

reimg = cv2.imread('demo.jpg')

resized = cv2.resize(reimg, None , fx=2, fy=2, interpolation = cv2.INTER_CUBIC)

cv2_imshow(resized)

simg = cv2.imread('demo.jpg')

s_resized = cv2.resize(reimg, None , fx=0.5, fy=0.5, interpolation = cv2.INTER_CUBIC)

cv2_imshow(s_resized)

